[workspace]
members = [
    "libdragon",
    "libdragon-sys",
    "libdragon-examples/*",
]
default-members = [
    "libdragon",
    "libdragon-sys",
]

package.rust-version = "1.75.0"
resolver = "2"

[profile.dev]
opt-level = 2 # "some optimizations"
